### ISSUE TITLE
Awtrix Weather ⛈️ + Forecast + 🌕️: Red border + Color Matrix explanation

### ISSUE THREAD

**Issue by Goldsucher** [jeeftor/HomeAssistant#18]
Hi jeeftor!

I use your Awtrix Weather Automation - Thanks for that!

Just a short question: Sometimes there is a red border around the weather information. I didn't find any documentation about that. So, What does that mean?

Thanks!

**Comment by appsfinder2** [comment]
that happen when not receiving weather updates check what ever bringing the weather into Home Assistant

**Comment by Goldsucher** [comment]
> that happen when not receiving weather updates check what ever bringing the weather into Home Assistant

ah thanks! This only happens very rarely, so it's not really a problem.

But could you please explain the color matrix. These are my values:

`{"-5": "#00008B","0": "#1E90FF","5": "#87CEFA","10": "#00FF00","15": "#FFFF00","20": "#FFA500","25": "#FF4500","30": "#FF0000"}`

So every square stands for an hour in the future? Somehow it doesn't make sense with my values. That would mean that it would be warmer at 3 a.m. than it is now, which is not the case:

![IMG_5845BA4EBC3B-1](https://github.com/jeeftor/HomeAssistant/assets/7906131/b2437910-c27e-46bb-8dd3-0b409dd26e68)

(square 5 to 8 from left)

Could you explain that?

**Comment by appsfinder2** [comment]
> > that happen when not receiving weather updates check what ever bringing the weather into Home Assistant
> 
> ah thanks! This only happens very rarely, so it's not really a problem.
> 
> But could you please explain the color matrix. These are my values:
> 
> `{"-5": "#00008B","0": "#1E90FF","5": "#87CEFA","10": "#00FF00","15": "#FFFF00","20": "#FFA500","25": "#FF4500","30": "#FF0000"}`
> 
> So every square stands for an hour in the future? Somehow it doesn't make sense with my values. That would mean that it would be warmer at 3 a.m. than it is now, which is not the case:
> 
> ![IMG_5845BA4EBC3B-1](https://private-user-images.githubusercontent.com/7906131/336216352-b2437910-c27e-46bb-8dd3-0b409dd26e68.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODMxMDIsIm5iZiI6MTcxNzQ4MjgwMiwicGF0aCI6Ii83OTA2MTMxLzMzNjIxNjM1Mi1iMjQzNzkxMC1jMjdlLTQ2YmItOGRkMy0wYjQwOWRkMjZlNjguanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA2MzMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwM2FlODMzNWVjNjJhMTBiMWVjMDA3YTA0Y2I4M2UzMmE2ZmI5NTJjZThjNjVkNmNmMDQzYjIwYTM4NDMzZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SUW5iYbzP1fVFYR7TH9Bzr_dRqgvMMDkRnlhkraC-qc)
> 
> (square 5 to 8 from left)
> 
> Could you explain that?

I think the line at bottom is the time of day 12 hours 

{"-5": "#00008B","0": "#1E90FF","5": "#87CEFA","10": "#00FF00","15": "#FFFF00","20": "#FFA500","25": "#FF4500","30": "#FF0000"} these are web colors for the temp e.g. -5 is #00008B and so on you can change these.

**Comment by Goldsucher** [comment]
Okay thanks! I just found out that openweathermap provides data only every 3 hours. Because of that I was confused about my colors.
Now I have switched to met.no (which has hourly forecast) and now it makes a lot more sense.
Thanks @appsfinder2
