### ISSUE TITLE
Weather blueprint error in ipgeolocation rest sensor example?

### ISSUE THREAD

**Issue by koenvangils** [jeeftor/HomeAssistant#5]
I think you accidentally included a minus prefix to the longitude in the example of the ipgeolocation rest sensor:

`resource: https://api.ipgeolocation.io/astronomy?lat=<LAT>&long=-<LON>&apiKey=<API_KEY>`

It looks like it should be:

`resource: https://api.ipgeolocation.io/astronomy?lat=<LAT>&long=<LON>&apiKey=<API_KEY>`

**Comment by jeeftor** [comment]
I guess you are correct :).. updated
