### ISSUE TITLE
Awtrix Weather: Error running automation

### ISSUE THREAD

**Issue by johnsturgeon** [jeeftor/HomeAssistant#8]
```
2023-09-16 08:29:30.149 ERROR (MainThread) [homeassistant.components.automation.awtrix_weather] Error rendering variables: UndefinedError: homeassistant.helpers.template.Wrapper object has no element 8
```

**Comment by jeeftor** [comment]
https://discord.com/channels/546407049148366859/1144672974083993732

(best way to get help I think)

**Comment by johnsturgeon** [comment]
Thanks, I'll give it a shot

**Comment by itstueben** [comment]
I have the same Problem. It seems that the discord channel not exsiting anymore
@jeeftor or @johnsturgeon  What was the solution here?

**Comment by johnsturgeon** [comment]
Discord channel most definitely still exists
https://discord.gg/cyBCpdx

My problem ended up being that I missed a variable on the blueprint.  Just thoroughly go through the blueprint and make sure you've filled in every single one.
